version: '3'
services:
  database:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: dev
      MYSQL_USER: dev
      MYSQL_PASSWORD: secret
    command: --init-file /data/application/init.sql
    volumes:
      - ./server/init.sql:/data/application/init.sql
    container_name: monitoring-service-database
