version: '3'
services:
  database:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: dev
      MYSQL_USER: dev
      MYSQL_PASSWORD: secret
    command: --init-file /data/application/init.sql
    volumes:
      - ./server/init.sql:/data/application/init.sql
    container_name: monitoring-service-database

  monitoring_service:
    depends_on:
      - database
    build: ./monitoring-service
    ports:
      - "8081:8881"
    container_name: monitoring-service
    environment:
      - DATABASE_HOST=database
      - DATABASE_USER=dev
      - DATABASE_PASSWORD=secret
      - DATABASE_NAME=dev
      - DATABASE_PORT=3306
